#!/bin/bash
# 
#  This utility is used to run regression tests on these models
#
#   regression_test [-o <output directory>]

# USAGE
print_usage () { 
    echo "Usage:"
    echo "        regression_test [-o <output directory>]";
}

# input variables
BPINSTALL="/Users/levistarrett/xtuml/m621.cli/BridgePoint.app/Contents/Eclipse"
OUT_DIR=

# parse arguments
DIRECTIVE=
for arg in $@; do
    if [[ $arg == "-o" ]]; then                     # set the directive
        DIRECTIVE=$arg
    elif [[ $DIRECTIVE == "-o" && $OUT_DIR == "" ]]; then           # only can set the output directory once
        OUT_DIR=$arg
    else
        print_usage
        exit 1
    fi
done

# if no out directory was given, give the current working directory
if [[ $OUT_DIR == "" ]]; then OUT_DIR=.; fi

XVFB=$(which xvfb-run)
if [[ $XVFB == "" ]]; then
  echo "Consider installing xvfb to run this suite headlessly.\n"
fi

# set up workspace
export WORKSPACE="/tmp/importwork"
export BPHOME=$BPINSTALL

# We have to create a workspace from a previously zipped one that contains a project 
# because CLI Import can't create a project for a single file model itself.  The latter would
# be much better.          
echo "Preparing workspace $WORKSPACE"
if [[ -d $WORKSPACE ]]; then
    rm -rf $WORKSPACE      
fi
unzip -q -o $BPINSTALL/tools/mc/bin/importworkspace.zip -d /tmp/

# lanch eclipse
echo "Launching an Eclipse command line instance..."
CLI_PORT_FILE=`mktemp`
python $BPINSTALL/tools/mc/bin/launch-cli.py launch $CLI_PORT_FILE
if [[ 0 != $? ]]; then
    echo "Eclipse launch failed."
    exit 1
fi
CLI_PORT=`cat $CLI_PORT_FILE`

# project counter
COUNTER=1

# Run tests
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d ../SAC/SAC_OOA -o $OUT_DIR/00 -n $CLI_PORT -l d$COUNTER
COUNTER=$[$COUNTER +1]
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9027-1 -o $OUT_DIR/01 -n $CLI_PORT -l d$COUNTER
COUNTER=$[$COUNTER +1]
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9027-2 -o $OUT_DIR/02 -n $CLI_PORT -l d$COUNTER
COUNTER=$[$COUNTER +1]
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9027-3 -o $OUT_DIR/03 -n $CLI_PORT -l d$COUNTER
COUNTER=$[$COUNTER +1]
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9027-4 -o $OUT_DIR/04 -n $CLI_PORT -l d$COUNTER
COUNTER=$[$COUNTER +1]
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9027-5 -o $OUT_DIR/05 -n $CLI_PORT -l d$COUNTER
COUNTER=$[$COUNTER +1]
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d ipv6   -o $OUT_DIR/06 -n $CLI_PORT -l d$COUNTER
COUNTER=$[$COUNTER +1]
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d pei    -o $OUT_DIR/07 -n $CLI_PORT -l d$COUNTER
COUNTER=$[$COUNTER +1]
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d maslsupsub -o $OUT_DIR/08 -n $CLI_PORT -l d$COUNTER
COUNTER=$[$COUNTER +1]
$XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d 9149_id -o $OUT_DIR/09 -n $CLI_PORT -l d$COUNTER

# shut down eclipse
python $BPINSTALL/tools/mc/bin/launch-cli.py cmd $CLI_PORT exit

find $OUT_DIR -name "diff_*" -exec ls -l {} \;
