#!/bin/bash
# 
#  This utility is used to run regression tests on these models
#
#   regression_test [-o <output directory>]

# USAGE
print_usage () { 
    echo "Usage:"
    echo "        regression_test [-o <output directory>]";
}

# input variables
BPINSTALL="/Users/levistarrett/xtuml/m625.cli/BridgePoint.app/Contents/Eclipse"
OUT_DIR=

# parse arguments
DIRECTIVE=
for arg in $@; do
    if [[ $arg == "-o" ]]; then                     # set the directive
        DIRECTIVE=$arg
    elif [[ $DIRECTIVE == "-o" && $OUT_DIR == "" ]]; then           # only can set the output directory once
        OUT_DIR=$arg
    else
        print_usage
        exit 1
    fi
done

# if no out directory was given, give the current working directory
if [[ $OUT_DIR == "" ]]; then OUT_DIR=.; fi

XVFB=$(which xvfb-run)
if [[ $XVFB == "" ]]; then
  echo "Consider installing xvfb to run this suite headlessly."
fi

# set up workspace
export WORKSPACE="/tmp/importwork"
if [[ -d $WORKSPACE ]]; then
	rm -rf $WORKSPACE
fi

export BPHOME=$BPINSTALL

# lanch eclipse
echo "Launching an Eclipse command line instance..."
$BPINSTALL/tools/mc/bin/CLI.sh Launch

# Run tests
COUNTER=1
while read TEST; do
    if [[ $TEST != "//"* ]]; then
        $XVFB $BPINSTALL/tools/mc/bin/masl_round_trip -d $TEST -o $OUT_DIR/$COUNTER
        COUNTER=$[$COUNTER +1]
    fi
done

# shut down eclipse
$BPINSTALL/tools/mc/bin/CLI.sh Launch -exit

find $OUT_DIR -name "diff_*" -exec ls -l {} \;
